Сделал разметку на Html
summertime-fms/karim-device pull request #1
Opened 2023-03-28 08:12 UTC by Zalgor1902

2023-03-29 07:45 UTC, summertime-fms requested changes

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +  <html>
lang давай добавим для доступности

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +	 <body>
Отступы должны быть единообразными. Есть способы форматировать автоматически. Например, prettier

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +        <header class="page-header">
я бы сократил до просто header  (не критично)

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                  <input class="search-menu" type="text" placeholder="Поиск по сайту">
type="search" + нужно обернуть в форму

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                  <button class="search-button">
чтобы кнопка отправляла данные нужно ей задать type="submit"

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                    <span class="visually-hidden">Найти</span>
В этом нет смысла ведь текст должен отображаться, а ты его прячешь этим классом. И тут вообще без спана можно, текст можно вставлять прямо в кнопку/

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                    <img class="search-menu-icon" src="" alt="Войти в аккаунт">
Это изображение не контентое а декоративное. Оно делается либо фоном через стили либо инлайновый свг. мы будем делать инлайновый свг - как именно расскажу на следующих разделах, а пока вот - https://htmlacademy.ru/blog/html/content-or-decor-img

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                    <img class="user-menu-icon" src="" alt="Сравнить">
Аналогично замечанию выше, все иконки мелкие - это не img

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +              <ul class="toggler-list">
Зачем тут список если внутри всего лишь один элемент? Я бы сделал просто кнопкой, ведь мы будем взаиомдействовать с этим элементом.

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +          <main class="main-inner">
Обычно в классе на этом теге нет необходимости, можно убрать я думаю

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                            <li class="catalog-filter-item">
Как и в случае с page-header -  ты добавляешь префикс к классу, тем самым делая его длиннее. Можно просто `filter` (не критично)

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                                    <input class="control-input" type="checkbox" name="Черный" checked>
неймы как и вообще все в разметке надо писать на английском. эти строки потом уходят на сервер и попадают в код, кириллица там не нужна)

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                                    <input class="control-input" type="radio" name="bluetooth" checked>
У тебя две одинаковые радиокнопки. Но они должны отличаться своим значением. Сейчас вне зависимости от того какую пользователь выберет - отправятся одни и те же данные ( да и вообще отправятся ли?..)

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                    <button class="product-show-more" type="button">Загрузить ещё</button>
Если в макете большинство кнпоок имеют схожие стили то имеет смысл выделить отдельный класс под них. Например, button. Так ты сократишь количество стилей

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +              <h2 class="visually-hidden">Адрес</h2>
имхо тут излишняя семантичность. Заголовок Адрес ниже тег Адрес, от заголовка можно отказаться

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +                  <a class="footer-social-link" href="https://t.me/htmlacademy">
Погугли про атрибуты nofollow noreferer - их лучше задавать когда ссылка ведет на ВНЕШНИЙ источник

2023-03-29 07:45 UTC, summertime-fms commented on catalog.html
> +          </footer>
Я бы отказался от заголовков, сделал бы секцию просто дивом. Я знаю что академия дает в примерах секции в футере - но секция уместна там где большой смысловой блок сайта (например - Наши товары, Контакты, Наши преимущества) а тут маленький блок - телефон + картинка

2023-03-30 06:10 UTC, Zalgor1902 commented on catalog.html
> +  <html>
Добавил lang="ru"

2023-03-30 06:11 UTC, Zalgor1902 commented on catalog.html
> +	 <body>
Хорошо, это плагин для vs code?

2023-03-30 06:15 UTC, Zalgor1902 commented on catalog.html
> +        <header class="page-header">
Да, так действительно удобнее

2023-03-30 06:19 UTC, Zalgor1902 commented on catalog.html
> +                  <input class="search-menu" type="text" placeholder="Поиск по сайту">
обернул в тег form, поменял с type="text" На type="search". Добавил атрибут name для тега input

2023-03-30 08:27 UTC, Zalgor1902 commented on catalog.html
> +                <img class="logo-device" src="" alt="Логотип device">
Удалил класс для img в навигации

2023-03-30 08:40 UTC, Zalgor1902 commented on catalog.html
> +          <main class="main-inner">
Можно как и в случае с header, Написать класс main?

2023-03-30 15:32 UTC, Zalgor1902 commented on catalog.html
> +                    <span class="visually-hidden">Найти</span>
Убрал тег span

2023-03-30 15:35 UTC, Zalgor1902 commented on catalog.html
> +                    <img class="user-menu-icon" src="" alt="Сравнить">
также убрал img

2023-03-30 15:47 UTC, Zalgor1902 commented on catalog.html
> +          <main class="main-inner">
пока оставлю, просто на главной странице тоже есть тег main, там другой класс

2023-03-30 15:51 UTC, Zalgor1902 commented on catalog.html
> +                                    <input class="control-input" type="checkbox" name="Черный" checked>
Переделал на английский)

2023-03-30 15:59 UTC, Zalgor1902 commented on catalog.html
> +                  <a class="footer-social-link" href="https://t.me/htmlacademy">
оке

2023-03-30 16:11 UTC, Zalgor1902 commented on catalog.html
> +          </footer>
изменю на div

2023-04-03 10:43 UTC, summertime-fms commented on catalog.html
> +	 <body>
да, его ставишь, потом выделяешь строки сколько надо и делаешь ctrl+shift + P и там выберешь в предложенном селекте форматнуть через prettier

2023-04-03 10:44 UTC, summertime-fms commented on catalog.html
> +                                    <input class="control-input" type="radio" name="bluetooth" checked>
тебе надо прикрутить value

2023-04-03 10:48 UTC, summertime-fms requested changes

2023-04-03 10:48 UTC, summertime-fms commented on index.html
> +        <section class="gallery-description">
А давай единой секцией сделаем весь экран - в однйо его части будет картинка а в другой описание + кнопки там всякие и характеристики по макету

2023-04-03 10:48 UTC, summertime-fms commented on index.html
> +          <h3 class="distance-title">800 м</h3>
можно попрообовать через dl сделать этот блок, будет семантичнее

2023-04-03 10:48 UTC, summertime-fms commented on index.html
> +            <img class="delivery-image" src="" alt="восклицательный знак">
Это декоративный элемент

2023-04-03 10:48 UTC, summertime-fms commented on index.html
> +            <li class="about-us-item">Меловые линии</li>
В принципе для упрощения ты можешь откааться тут от классов так как внутри списка будут только li
Cтилизовать можно от обертки - .about-is-list li {}

2023-04-03 10:48 UTC, summertime-fms commented on index.html
> +            <input type="text" name="subscribe-email" placeholder="Ваш e-mail">
type email + reqiured

2023-04-03 17:32 UTC, Zalgor1902 commented on index.html
> +        <section class="gallery-description">
Хорошо, оберну их в одну секцию

2023-04-03 17:51 UTC, Zalgor1902 commented on index.html
> +            <img class="delivery-image" src="" alt="восклицательный знак">
Добавил как декоративный

2023-04-03 17:53 UTC, Zalgor1902 commented on index.html
> +            <li class="about-us-item">Меловые линии</li>
Убрал класс у списка

2023-04-03 18:00 UTC, Zalgor1902 commented on index.html
> +            <input type="text" name="subscribe-email" placeholder="Ваш e-mail">
Добавил

2023-04-06 10:54 UTC, summertime-fms requested changes

2023-04-06 10:54 UTC, summertime-fms commented on styles/styles.css
> +    font-family: "raleway", sans-serif;
Давай запасной пропишем на всякий.  Arial например. Это хорошая практика

2023-04-06 10:54 UTC, summertime-fms commented on styles/styles.css
> +    background-color: #FFE17F;
надо к единому формату привести цвета чтобы было по кодгайду академии. А то где то капсом а где то маленькими

2023-04-06 10:54 UTC, summertime-fms commented on styles/styles.css
> +    color: #000000;
Чтобы везде черный цвет не прописывать можно его в body прописать и он отнаследуется ко всем элементам. Переопределить цвет где нужно проще чем каждому элементу задавать черный

2023-04-06 10:54 UTC, summertime-fms commented on styles/styles.css
> +    padding: 51px 31px 51px 32px;
padding: 51px 32px;
можно сокращать

2023-04-06 10:54 UTC, summertime-fms commented on styles/styles.css
> +    font-family: "rubik", sans-serif;
Аналогично как и в замечании с color  - пропиши один раз в body и не придется в каждом правиле это повторять

2023-04-07 06:19 UTC, Zalgor1902 commented on styles/styles.css
> +    padding: 51px 31px 51px 32px;
Хорошо

2023-04-08 08:37 UTC, Zalgor1902 commented on styles/styles.css
> +    font-family: "rubik", sans-serif;
Хорошо

2023-04-08 19:51 UTC, merged